set(_CATKIN_CURRENT_PACKAGE "pja")
set(pja_VERSION "0.0.1")
set(pja_MAINTAINER "Ji Zhang <zhangji@cmu.edu>")
set(pja_PACKAGE_FORMAT "1")
set(pja_BUILD_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "message_filters" "pcl_ros" "nav_core")
set(pja_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "message_filters" "pcl_ros" "nav_core")
set(pja_BUILDTOOL_DEPENDS "catkin")
set(pja_BUILDTOOL_EXPORT_DEPENDS )
set(pja_EXEC_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "message_filters" "pcl_ros" "nav_core")
set(pja_RUN_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "message_filters" "pcl_ros" "nav_core")
set(pja_TEST_DEPENDS )
set(pja_DOC_DEPENDS )
set(pja_URL_WEBSITE "")
set(pja_URL_BUGTRACKER "")
set(pja_URL_REPOSITORY "")
set(pja_DEPRECATED "")