set(_CATKIN_CURRENT_PACKAGE "ouster_description")
set(ouster_description_VERSION "1.0.7")
set(ouster_description_MAINTAINER "Wil Selby <accounts@wilselby.com>")
set(ouster_description_PACKAGE_FORMAT "2")
set(ouster_description_BUILD_DEPENDS )
set(ouster_description_BUILD_EXPORT_DEPENDS )
set(ouster_description_BUILDTOOL_DEPENDS "catkin")
set(ouster_description_BUILDTOOL_EXPORT_DEPENDS )
set(ouster_description_EXEC_DEPENDS "urdf" "xacro")
set(ouster_description_RUN_DEPENDS "urdf" "xacro")
set(ouster_description_TEST_DEPENDS "rostest")
set(ouster_description_DOC_DEPENDS )
set(ouster_description_URL_WEBSITE "")
set(ouster_description_URL_BUGTRACKER "")
set(ouster_description_URL_REPOSITORY "")
set(ouster_description_DEPRECATED "")