(cl:defpackage ouster_ros-srv
  (:use )
  (:export
   "OSCONFIGSRV"
   "<OSCONFIGSRV-REQUEST>"
   "OSCONFIGSRV-REQUEST"
   "<OSCONFIGSRV-RESPONSE>"
   "OSCONFIGSRV-RESPONSE"
   "OSCONFIGSRVWRITE"
   "<OSCONFIGSRVWRITE-REQUEST>"
   "OSCONFIGSRVWRITE-REQUEST"
   "<OSCONFIGSRVWRITE-RESPONSE>"
   "OSCONFIGSRVWRITE-RESPONSE"
  ))

