<?xml version="1.0"?>

<robot name="base" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define a number of dimensions using properties -->
  <xacro:property name="base_size_x" value="0.726" />
  <xacro:property name="base_size_y" value="0.425" />
  <xacro:property name="base_size_z" value="0.20" />
  <xacro:property name="wheel_offset_x" value="0.228" />  <!--${base_size_x/2}-${wheel_radius}-->
  <xacro:property name="wheel_offset_y" value="0.2675" />  <!--${base_size_y/2}++${wheel_length/2}+0.015-->
  <xacro:property name="wheel_offset_z" value="-0.065" />  <!--${base_size_z/2}-${wheel_radius}+0.1-->
  <xacro:property name="wheel_radius" value="0.135" />
  <xacro:property name="PI" value="3.1415" />
  
  <xacro:include filename="$(find pja)/urdf/wheel.urdf.xacro" />

  <!-- The base xacro macro -->
  <xacro:macro name="base" params="name color">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
        </geometry>
        <material name="${color}" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${base_size_x} ${wheel_offset_y*2 + wheel_length} ${base_size_z}" />
        </geometry>
      </collision>
    </link>
  

  <!-- Add the drive wheels -->
   <xacro:wheel parent="${name}" suffix="l1"  color="Black">
      <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="${PI/2} 0 0 " />
   </xacro:wheel>

    <xacro:wheel parent="${name}" suffix="l2"  color="Black">
      <origin xyz="${-wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="${PI/2} 0 0 " />
   </xacro:wheel>

   <xacro:wheel parent="${name}" suffix="r1"  color="Black">
      <origin xyz="${wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="${-PI/2} 0 0 " />
   </xacro:wheel>

   <xacro:wheel parent="${name}" suffix="r2"  color="Black">
      <origin xyz="${-wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="${-PI/2} 0 0 " />
   </xacro:wheel> 



  </xacro:macro>
    
</robot>
