// Generated by gencpp from file ouster_ros/OSConfigSrvWrite.msg
// DO NOT EDIT!


#ifndef OUSTER_ROS_MESSAGE_OSCONFIGSRVWRITE_H
#define OUSTER_ROS_MESSAGE_OSCONFIGSRVWRITE_H

#include <ros/service_traits.h>


#include <ouster_ros/OSConfigSrvWriteRequest.h>
#include <ouster_ros/OSConfigSrvWriteResponse.h>


namespace ouster_ros
{

struct OSConfigSrvWrite
{

typedef OSConfigSrvWriteRequest Request;
typedef OSConfigSrvWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OSConfigSrvWrite
} // namespace ouster_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ouster_ros::OSConfigSrvWrite > {
  static const char* value()
  {
    return "a9c18328c22f699f1b91d9e4167cda4a";
  }

  static const char* value(const ::ouster_ros::OSConfigSrvWrite&) { return value(); }
};

template<>
struct DataType< ::ouster_ros::OSConfigSrvWrite > {
  static const char* value()
  {
    return "ouster_ros/OSConfigSrvWrite";
  }

  static const char* value(const ::ouster_ros::OSConfigSrvWrite&) { return value(); }
};


// service_traits::MD5Sum< ::ouster_ros::OSConfigSrvWriteRequest> should match
// service_traits::MD5Sum< ::ouster_ros::OSConfigSrvWrite >
template<>
struct MD5Sum< ::ouster_ros::OSConfigSrvWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::OSConfigSrvWrite >::value();
  }
  static const char* value(const ::ouster_ros::OSConfigSrvWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::OSConfigSrvWriteRequest> should match
// service_traits::DataType< ::ouster_ros::OSConfigSrvWrite >
template<>
struct DataType< ::ouster_ros::OSConfigSrvWriteRequest>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::OSConfigSrvWrite >::value();
  }
  static const char* value(const ::ouster_ros::OSConfigSrvWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ouster_ros::OSConfigSrvWriteResponse> should match
// service_traits::MD5Sum< ::ouster_ros::OSConfigSrvWrite >
template<>
struct MD5Sum< ::ouster_ros::OSConfigSrvWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::OSConfigSrvWrite >::value();
  }
  static const char* value(const ::ouster_ros::OSConfigSrvWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::OSConfigSrvWriteResponse> should match
// service_traits::DataType< ::ouster_ros::OSConfigSrvWrite >
template<>
struct DataType< ::ouster_ros::OSConfigSrvWriteResponse>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::OSConfigSrvWrite >::value();
  }
  static const char* value(const ::ouster_ros::OSConfigSrvWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OUSTER_ROS_MESSAGE_OSCONFIGSRVWRITE_H
