// Generated by gencpp from file ouster_ros/OSConfigSrvWriteResponse.msg
// DO NOT EDIT!


#ifndef OUSTER_ROS_MESSAGE_OSCONFIGSRVWRITERESPONSE_H
#define OUSTER_ROS_MESSAGE_OSCONFIGSRVWRITERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ouster_ros
{
template <class ContainerAllocator>
struct OSConfigSrvWriteResponse_
{
  typedef OSConfigSrvWriteResponse_<ContainerAllocator> Type;

  OSConfigSrvWriteResponse_()
    : res(false)  {
    }
  OSConfigSrvWriteResponse_(const ContainerAllocator& _alloc)
    : res(false)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OSConfigSrvWriteResponse_

typedef ::ouster_ros::OSConfigSrvWriteResponse_<std::allocator<void> > OSConfigSrvWriteResponse;

typedef boost::shared_ptr< ::ouster_ros::OSConfigSrvWriteResponse > OSConfigSrvWriteResponsePtr;
typedef boost::shared_ptr< ::ouster_ros::OSConfigSrvWriteResponse const> OSConfigSrvWriteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator1> & lhs, const ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator1> & lhs, const ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ouster_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e27848a10f8e7e4030443887dfea101b";
  }

  static const char* value(const ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe27848a10f8e7e40ULL;
  static const uint64_t static_value2 = 0x30443887dfea101bULL;
};

template<class ContainerAllocator>
struct DataType< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ouster_ros/OSConfigSrvWriteResponse";
  }

  static const char* value(const ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool res\n"
"\n"
;
  }

  static const char* value(const ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OSConfigSrvWriteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ouster_ros::OSConfigSrvWriteResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OUSTER_ROS_MESSAGE_OSCONFIGSRVWRITERESPONSE_H
